# Generated by Django 2.0.4 on 2018-04-22 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('number_commit', models.AutoField(primary_key=True, serialize=False, verbose_name='评论id')),
                ('blog_commit', models.TextField(verbose_name='评论内容')),
                ('user_name', models.CharField(blank=True, max_length=50, null=True)),
                ('time_commit', models.DateField(auto_now_add=True, verbose_name='创建日期')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('from_id', models.ForeignKey(blank=True, default=None, null=True, on_delete=None, related_name='children', to='comments.Comment', verbose_name='回复用户')),
                ('to_blog_id', models.ForeignKey(on_delete=None, to='blog.Blog', verbose_name='关联博文id')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
            },
        ),
    ]
